apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-nginx
  name: eks-nginx
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eks-nginx
  template:
    metadata:
      labels:
        app: eks-nginx
    spec:
      containers:
      - image: powermvp/netflix:v1.0

        name: eks-nginx
